#ifndef INC_PROTECTION_PARAM_H_
#define INC_PROTECTION_PARAM_H_

#define PROTECTION_TEMP_WARNING_C     70
#define PROTECTION_TEMP_ERROR_C       85
#define PROTECTION_TEMP_HYSTERESIS_C   5

#endif /* INC_PROTECTION_PARAM_H_ */
